# Generated by Django 5.0.6 on 2024-05-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=50)),
                ('i_category', models.IntegerField(choices=[(1, 'veg'), (2, 'non-veg')], verbose_name='category')),
                ('i_desc', models.TextField()),
                ('i_price', models.FloatField()),
            ],
        ),
    ]
