# Generated by Django 5.0.6 on 2024-06-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_platter_qty_alter_profile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platter',
            old_name='i_id',
            new_name='product',
        ),
    ]
