# Generated by Django 5.0.6 on 2024-06-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_i_id_platter_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platter',
            old_name='user_id',
            new_name='user',
        ),
    ]
