# Generated by Django 5.0.6 on 2024-07-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_user_id_platter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platter',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
